typography_spectrum: 0.4039506169501692
color:
  brandStrength: 0.23561695218086243
  lightness: 0.17677908693440259
  saturation: 0.2833088575862348
  rhythmicContrast: 0.8516719499602914
  brandColors:
    - '#595241'
    - '#B8AE9C'
    - '#FFFFFF'
    - '#ACCFCC'
    - '#8A0917'
layout_spectrum: 0.3294210387393832
name: Barkers Bites
navigation:
  - name: Projections in the Forest
    id: b83f040c-fbc7-46ba-a1df-f46a71fbbb33
    type: content
  - name: 'Interview: Artist Ryan McGinness on Designing for Hennessy'
    id: d9c2c758-ed8c-48f9-88b9-6b4fa32245e4
    type: content
  - name: About us
    url: >-
      https://testing.thegrid.io/app/navcreate/choose?siteID=d0dec508-58f3-475b-a48a-ecb37b9c456d
    type: external
title: 'Finally, hipster food for the masses!'
description: sign up now or hold you peace
